CREATE DATABASE hospital;

USE hospital;

CREATE TABLE IF NOT EXISTS users (
	`id` INT(11) AUTO_INCREMENT,
	`username` VARCHAR(50) NOT NULL UNIQUE,
	`password` CHAR(60) NOT NULL,
	PRIMARY KEY (`id`)
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;
