CREATE DATABASE hospital;

USE hospital;

CREATE TABLE IF NOT EXISTS users (
	`id` INT(11) AUTO_INCREMENT,
	`username` VARCHAR(50) NOT NULL UNIQUE,
	`password` CHAR(60) NOT NULL,
	PRIMARY KEY (`id`)
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

CREATE TABLE IF NOT EXISTS auth_tokens (
	`id` INTEGER(11) NOT NULL AUTO_INCREMENT,
	`selector` CHAR(12),
	`token` CHAR(64),
	`user_id` INTEGER(11) NOT NULL,
	`expires` DATETIME,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`user_id`) REFERENCES users (`id`) ON DELETE CASCADE
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci AUTO_INCREMENT 1;

