CREATE TABLE IF NOT EXISTS resturant (
id VARCHAR2 UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY,
address VARCHAR2 DEFAULT NULL,
city VARCHAR2 DEFAULT NULL,
state CHAR(2) DEFAULT NULL,
zipcode VARCHAR2,
phonenumber CHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;
